### ISSUE TITLE
Code missing

### ISSUE THREAD

**Issue by francescvolgger** [petrasvestartas/OpenNest#3]
Hello petras, 
i would like to make some variations of the grasshopper node. 
there are some parts of youre code missing. could you upload them ?
like openNestSolver.cs, openNestCOmponent.cs or the deepnestlib. i could find the deepnestlib somewhere else, but dont know if you made some changes or not.
that would be really helpfull 👍 
thnx for your great work

**Comment by petrasvestartas** [comment]
I uploaded the new project with OpenNestlib for RhinoPlugin that shows basic sample how to user OpenNest library
